### ISSUE TITLE
uploading CSV files does not work for me

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-maps-with-google-sheets#121]
@ilyankou -- Uploading CSV files to the GitHub repo does not work for me in the Sept 12th version of the code you created, or the newer version I tried to update today.

Here's a summary of my tests and error screenshots

1) I started with today's code, based on the CDN updates I made (see my other issue), and I hope I didn't screw up!
I pulled the new code into a new repo for testing
https://github.com/JackDougherty/lmwgs-testing
The map loaded fine when it pulled data only from the Google Sheet
But when I downloaded the Options.csv etc. files and uploaded them to the root level, the map will not load
https://jackdougherty.github.io/lmwgs-testing/
See error message about "Uncaught TypeError: Cannot read prop 'lat' of undefined" (referring to Projection.SphericalMercator.js.24)
<img width="1382" alt="lmwgs-testing-error" src="https://user-images.githubusercontent.com/649719/94379361-bfd40080-00fd-11eb-8227-4a9fa1df425a.png">
Same error message if I named the files in lower-case (options.csv, etc.)
And if I upload them into a subfolder named csv, then the map works but only because it's pulling directly from the Google Sheet

2) So I went back to the version of the code you created around Sept 12th 
https://github.com/HandsOnDataViz/leaflet-maps-with-google-sheets/tree/0bfec18497bf1de783e1b345f93a70006f99f37b
and downloaded it to my local computer
and tried to upload the same files (Options.csv), but the map still would not load, whether upper- or lower-case letters
But it has a slightly different error message: "Uncaught TypeError: Cannot read prop 'lat' of undefined" (referring to Leaflet.js:5)
<img width="1395" alt="lmwgs-sept12-error" src="https://user-images.githubusercontent.com/649719/94379479-92d41d80-00fe-11eb-866a-b45b08fa6eb3.png">

**Comment by ilyankou** [comment]
Jack–

Thank you for testing this. Please update your local copy to include the changes that I have just pushed, and try again. I kept the csv- folder (just remove the minus sign to see how it works with data from a CSV). You can then remove the folder altogether.

**Comment by JackDougherty** [comment]
Ilya -- Thanks, this is much better! But the Polygons.csv file is still not loading, either in the main repo or my test version. Here's the error screenshot.

<img width="1148" alt="error-no-polygons" src="https://user-images.githubusercontent.com/649719/94450477-5692d280-017b-11eb-9537-f24f7210e5c4.png">

**Comment by ilyankou** [comment]
Thank you for catching this (it was working for my local server, but the reason was a typo, I put `../` instead of `./`). Should be all set now.

**Comment by JackDougherty** [comment]
Everything seems to be working with the CSV file uploads EXCEPT for one thing: the script is searching for Polygons2.csv, even though only Polygons.csv and Polygons1.csv exist.

Here's the error message on my local server, using my updated test code. I received the same error using your current repo code, too.

I failed to push this test to GitHub Pages, both for my test repo and the main repo, because of GitHub "page build error." Usually that turns out to be a separate issue with GitHub, but so far there's no alert at https://www.githubstatus.com/, so figured it was worth mentioning here.

<img width="1344" alt="error-polygons2" src="https://user-images.githubusercontent.com/649719/94466548-9bc0ff80-018f-11eb-9236-c510282ecc50.png">

**Comment by ilyankou** [comment]
This is normal behavior -- we try to fetch all files in order (Polygons, Polygons1, Polygons2, ...) as we don't know how many of them there are -- and we keep going until we get this "error". As soon as error is encountered, we stop reading polygons and moving on to initializing the map.

I got the same error for a different repository -- definitely a GitHub issue.

**Comment by JackDougherty** [comment]
I don't think this "Polygons2.csv" error is normal, because it's preventing the map from displaying. See screenshot of the current repo, with csv folder, on my local server. No map appears.

<img width="1384" alt="error-not-normal-behavior" src="https://user-images.githubusercontent.com/649719/94468094-e5aae500-0191-11eb-99f4-b943a21e434d.png">

**Comment by ilyankou** [comment]
@JackDougherty 

Please try to solve the second error (polygons-hartord-parks.geojson). Which Google Sheet are you using? You may need to change `geometry` to `geodata` folder name in your Google Sheet.

**Comment by JackDougherty** [comment]
Thanks for catching my error! Sorry about that.... and thanks for all of the code updates.
